version: 2.1
orbs:
  azure-cli: circleci/azure-cli@1.2.2

jobs:
          
  build-dockerhub:
    docker:
      - image: cimg/base:2022.06
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - setup_remote_docker:
          version: 20.10.14
      - checkout
      - run: |
          docker build -t braght/cyber-front .
      - run: |
          echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - run: |
          docker push braght/cyber-front


  azure-deploy:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - azure-cli/install
      - run: |
          az login -u $AZURE_USERNAME -p $AZURE_PASSWORD
      - run: |
          az container create --resource-group cyber-rg --name cyber-front-container --image braght/cyber-front:latest --dns-name-label cyber-front --ports 80 \
          --environment-variables 'Api_Address'=$Api_Address


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  cyber-frontend-build-deploy-workflow:
    jobs:
      - build-dockerhub:
          filters:
            branches:
              only:
                - main
          context: DOCKER_HUB
